### PR TITLE
Integrate skeleton-ansible-role

### LINKED ISSUE #1: Rewrite poorly written test
# 🐛 Bug Report #

[This test](https://github.com/cisagov/ansible-role-libselinux-python/blob/446d6d7917a7b24af57ea3eb5cddc7475b8532d2/molecule/default/tests/test_default.py#L13-L21) is poorly written and should be reworked.  The number of packages installed on Fedora and non-Fedora systems happens to be the same, so it works here, but in general when using `pytest.mark.parametrize` with multiple parameters [the parameters must have the same number of possible values](https://docs.pytest.org/en/stable/parametrize.html).

See also the discussion [here](https://github.com/cisagov/ansible-role-xfce-cool/pull/3#discussion_r542545230)

### LINKED ISSUE #2: Pull in upstream updates
# 🐛 Bug Report #

This Ansible role is _waaaay_ behind the times.  It doesn't have a `.github` directory at all, much less a [lineage](https://github.com/cisagov/action-lineage) configuration or a GitHub Actions workflow.  It must be brought into the light.

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR updates this project by integrating [cisagov/skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role). This allows this project to take advantage of the [lineage](https://github.com/cisagov/action-lineage) maintenance model.

## 💭 Motivation and Context ##

This will close #2 and #1 while I'm here. It's good to have all of our actively used Ansible roles on our framework for automated updates and weekly health builds with [action-apb](https://github.com/cisagov/action-apb).

## 🧪 Testing ##

Automated tests pass.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [x] Tests have been added and/or modified to cover the changes in this PR.
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
Excellent work!  My only ask is to use the variable `ansible_distribution_release` instead of `ansible_distribution_version`, as I recently did in cisagov/ansible-role-xfce#10.  I somehow didn't realize this variable existed before, but it allows you to create a single `vars/Debian_stretch.yml` file instead of the multiple `vars/Debian_9[.X].yml` files.

**Comment by mcdonnnj** [comment]
> 
> 
> Excellent work! My only ask is to use the variable `ansible_distribution_release` instead of `ansible_distribution_version`, as I recently did in [cisagov/ansible-role-xfce#10](https://github.com/cisagov/ansible-role-xfce/pull/10). I somehow didn't realize this variable existed before, but it allows you to create a single `vars/Debian_stretch.yml` file instead of the multiple `vars/Debian_9[.X].yml` files.

Ah, that's a nice change. Please see 24d40ae for the switch in this project.

**Review by jsf9k — APPROVED** [review]

**Comment by jsf9k** [comment]
> Ah, that's a nice change. Please see [24d40ae](https://github.com/cisagov/ansible-role-libselinux-python/commit/24d40ae0b863986f213f2236d2249dd3946a02b6) for the switch in this project.

Thanks for changing that.

**Review by dav3r — APPROVED** [review]
Great job on this! 🎯

**Pull request merged**
